name: Build and Push to GHCR

on:
  push:
    branches: [main, dev]

jobs:
  call-reusable:
    uses: ./.github/workflows/reusable-build.yml
    secrets:
      registry_password: ${{ secrets.GITHUB_TOKEN }}
    with:
      registry: ghcr.io
      username: ${{ github.actor }}
      image_namespace: ghcr.io
