name: Build and Push to Docker Hub

on:
  push:
    branches: [main, dev]

jobs:
  call-reusable:
    uses: ./.github/workflows/reusable-build.yml
    secrets:
      registry_password: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      registry: docker.io
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      image_namespace: ${{ secrets.DOCKERHUB_USERNAME }}
