# .github/workflows/docker-ghcr.yml
name: Build and Push to GHCR

on:
  push:
    branches: [main, dev]

jobs:
  call-reusable:
    uses: ./.github/workflows/reusable-build.yml
    with:
      registry: ghcr.io
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}
      image_namespace: ghcr.io
