# .github/workflows/docker-hub.yml
name: Build and Push to Docker Hub

on:
  push:
    branches: [main, dev]

jobs:
  call-reusable:
    uses: ./.github/workflows/reusable-build.yml
    with:
      registry: docker.io
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}
      image_namespace: ${{ secrets.DOCKERHUB_USERNAME }}
